name: Build and Publish NuGet Packages

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: false
  release:
    types: [published]

jobs:
  build-main-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Determine Package Version
        id: get-version
        run: |
            if [ "${{ github.event.release.tag_name }}" ]; then
                echo "package_version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            else
                echo "package_version=${{ github.event.inputs.package_version }}" >> $GITHUB_OUTPUT
            fi

      - name: Restore dependencies for the main package
        run: dotnet restore ./SemanticKernelPooling/SemanticKernelPooling.csproj

      - name: Build main package
        run: dotnet build ./SemanticKernelPooling/SemanticKernelPooling.csproj --configuration Release

      - name: Pack main package
        run: dotnet pack -c Release -p:PackageVersion=${{ steps.get-version.outputs.package_version }} /p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/SemanticKernelPooling/master/README.md" ./SemanticKernelPooling/SemanticKernelPooling.csproj --output ./nupkgs

      - name: Publish main package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
